version: '3.8'

services:
  nephrite-redis-server:
    image: 'redis:7.2.3-alpine3.19'
    networks:
      - network
    ports:
      - ${BULL_REDIS_PORT}:${BULL_REDIS_PORT}

  postgres:
    build: ./database
    env_file:
      - .env
    ports:
      - 5433:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always
    volumes:
      - './database/nephrite_test_dump.sql:/nephrite_test_dump.sql'
      - './database/restore.sh:/docker-entrypoint-initdb.d/restore.sh'
      - database:/var/lib/postgresql/data
    networks:
      - network

  server:
    build:
      context: './server'
    image: nephrite-server
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    depends_on:
      - nephrite-redis-server
      - postgres
    volumes:
      - logs:/usr/src/app/logs
      - ./server/src:/usr/src/app/src
    networks:
      - network

  client:
    build:
      context: './client'
    image: nephrite-client
    env_file:
      - '.env'
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    restart: on-failure
    depends_on:
      - server
    volumes:
      - ./client/src:/usr/src/app/src
    networks:
      - network

volumes:
  logs:
  database:
  pgadmin-data:

networks:
  network:
    driver: bridge
